app.name = "spark-analysis"

kafka.bootstrap.servers = "kafka:9092"

kafka.output.topic = "ANALYSIS_RESULTS"
kafka.startingOffsets = "earliest"
kafka.checkpointLocation = "/tmp/spark-checkpoints/traffic-analysis"

; analysis.names = "pollution,traffic"
analysis.names="traffic"
analysis.topic.mappings="pollution:EMISSIONS;traffic:FCD"

window.type = "tumbling"
window.length = "60 seconds"
window.slide = "10 seconds"

watermark.delay = "30 seconds"
trigger.interval = "5 seconds"



