app.name = "flink-analysis"

kafka.bootstrap.servers = "kafka:9092"
kafka.input.topics = "EMISSIONS,FCD"
kafka.output.topic = "ANALYSIS_RESULTS"
kafka.startingOffsets = "earliest"
kafka.checkpointLocation = "file:///tmp/flink-checkpoints/traffic-analysis"

analysis.names = "pollution,traffic"

window.type = "tumbling"
window.length = "60 seconds"
window.slide = "10 seconds"

watermark.delay = "30 seconds"
trigger.interval = "5 seconds"
